### PR TITLE
Make CA Bundle Path configurable

### LINKED ISSUE #329: configuration of custom ca-bundle
###### Environment

- mod_auth_openidc-2.3.3 (compiled from source)
- apache httpd-2.4.27 
- openssl-1.0.1f
- jansson-2.10
- cjose-0.5.1 
- curl-7.19.7 (distro)
- platform/distro RedHat-6

###### Expected behaviour
If the https-certificate of the IDP (e.g. keycloak) was signed by a local CA, it should be possible to configure a special ca-bundle that includes this CA. (like mod_proxy does: `SSLProxyCACertificateFile`)
This would be helpful for Test-Setups where you don't want to buy a certificate of one of the established CAs.
 

###### Actual behaviour
It is not possible to set an alternative ca-bundle. Also the Environment-Variable CURL_CA_BUNDLE used by curl doen't work cause it is only evaluated by curl itself not by libcurl.so 

###### Minimized example
**httpd_config:**
```
# Server config
# IDP e.g: a keycloak placed in my intranet;  SSL-certificate signed by MY-LOCAL-CA  
# client "TEST"
OIDCProviderMetadataURL https://mykeycloak-test.local:8443/auth/realms/TEST/.well-known/openid-configuration
```

###### Configuration and Log files

**httpd_error_log:**
```
oidc_util_http_call: curl_easy_perform() failed on: https://mykeycloak-test.local:8443/auth/realms/.well-known/openid-configuration (SSL certificate problem: unable to get local issuer certificate)
```

### PR DESCRIPTION
**Pull request by chris468**
Added a configuration option to specify the path of the CA Bundle for curl
Fixes #329 

### Testing
- `make test` passes
- I can log in with google without specifying a CA bundle path
- I can log with a locally hosted OpenID Connect server that uses a certificate signed by a test CA when I specify a bundle path containing the test CA:
    `OIDCCABundlePath "/path/to/my/bundle.crt"`
    with both absolute and relative paths

### CODE REVIEW

File: src/config.c [hunk 1]
```diff
@@ -3247,5 +3254,11 @@ const command_rec oidc_config_cmds[] = {
 				RSRC_CONF|ACCESS_CONF|OR_AUTHCFG,
 				"Define the cookie prefix for the state cookie."),
 
+		AP_INIT_TAKE1(OIDCCABundlePath,
+				oidc_set_string_slot,
```
Comment (chris468) [inline src/config.c:3258]: @spanglerco suggested calling `ap_server_root_relative` so that relative paths will work as well. I'll update with that change.

**Comment by zandbelt** [comment]
LGTM, can you add something to the ChangeLog and add yourselves to the AUTHORS file?
